### ISSUE TITLE
Type of start/end columns in cooler bins is int32

### ISSUE THREAD

**Issue by sergpolly** [4dn-dcic/hic2cool#20]
Not an issue at all, but something to have in mind for downstream processing:
```cooler.bins()[:]```-DataFrame ends up having ```np.int32``` dtypes for ```start/end``` columns,  which is different from a typical cooler file that one gets using cooler binning, it's ```int64``` there. I'm not sure if there is a standard for that (@nvictus ?)

This, for example, lead to a tough to debug situation in our dot-calling script, as we were clustering ```start1``` , ```start2``` coordinates of a bunch of peaks and got an integer overflow error with some messed up clusters as a result.

**Comment by carlvitzthum** [comment]
@sergpolly Thanks for identifying this issue, and sorry it's taken me so long to respond. I will make a hic2cool release soon that addresses changing the dtype to `np.int64`.

**Comment by carlvitzthum** [comment]
Following up on this: I am not sure that `np.int64` is the correct type for `start/end`. `np.int32` may in fact be correct. This is based off of the [cooler schema](https://cooler.readthedocs.io/en/latest/schema.html#data-collection) and the source code ([here](https://github.com/mirnylab/cooler/blob/00d9ab4de4c504c5a60a7d49bf33f5670f361182/cooler/create/__init__.py#L10) and [here](https://github.com/mirnylab/cooler/blob/00d9ab4de4c504c5a60a7d49bf33f5670f361182/cooler/create/_create.py#L132)).

It could be that this issue is just old and they have been updated. Do you think this change still needs to be made?

**Comment by sergpolly** [comment]
looks like I've confused `bins_1/2` and `start/end1/2` at some point - former are `int64` according to `schema`, whereas latter ones are `int32` (which is a bit strange - but should be discussed elsewhere) , i.e. I was clustering by `bins_1/2` initially and than switched to `start1/2` AND tried to use `.cool` produced by `hic2cool` at the same time - which caused the confusion that I wanted to document somewhere - that's how it ended up in this issue and here: https://github.com/mirnylab/cooltools/blob/6a6857f7cc973ba589d8b47ae90b9325d3190e8b/cooltools/dotfinder.py#L123

sorry about that @carlvitzthum - probably nothing needs to be changed about the types, as `hic2cool` follows the `schema` precisely.

**Comment by carlvitzthum** [comment]
Okay, thanks for following up.
